/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    testImplementation("net.serenity-bdd:serenity-core:2.3.2")
    testImplementation("org.slf4j:slf4j-simple:1.7.7")
    testImplementation("net.serenity-bdd:serenity-junit:2.3.2")
    testImplementation("junit:junit:4.12")
}

group = "com.social"
version = "1.0-SNAPSHOT"
description = "Serenity project with JUnit and WebDriver"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}
